### ISSUE TITLE
run the code you mentioned has some wrong

### ISSUE THREAD

**Issue by littleolex** [untitled-ai/self_supervised#11]
Traceback (most recent call last):
  File "E:/git/self_supervised/train_blog.py", line 42, in <module>
    main()
  File "E:/git/self_supervised/train_blog.py", line 33, in main
    method = MoCoMethod(config)
  File "E:\git\self_supervised\moco.py", line 115, in __init__
    self.hparams = AttributeDict(attr.asdict(hparams))
  File "E:\software\anaconda3\envs\pytorch_1_7\lib\site-packages\torch\nn\modules\module.py", line 826, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by UncleSan** [comment]
@littleolex  I meet the same problem.  Have you solve it?

**Comment by joshalbrecht** [comment]
This is likely because some dependency has changed and you're now using a newer version than we used.

Try installing the versions mentioned in the requirements.txt as == instead of >=

Also we used pytorch 1.6, and it looks like you have 1.7

It's likely that this is basically caused by a newer version of pytorch lightning as described here: https://discuss.pytorch.org/t/pytorch-lightning-module-cant-set-attribute-error/121125

**Comment by Fubuki901** [comment]
If you use some latest version of pytorch-lightning, you will meet this problem.
`self.hparams = AttributeDict(attr.asdict(hparams))`
Replace that with the following line.
`self.save_hyperparameters(AttributeDict(attr.asdict(hparams)))`
